"""
Auto-generated entity mappings for pentagi-taxonomy.
DO NOT EDIT - this file is generated from entities.yml
"""

from .nodes import Target, Vulnerability, Tool, TechnicalFinding, AttackTechnique, TestPhase, Credential, ExploitCode, AuthenticationAttempt, DatabaseMetadata, ExploitationAttempt, SessionInfo, FileSystemAccess, XMLPayload
from .edges import HasVulnerability, UsedAgainst, Exploits, DiscoveredIn, LeadsTo, Targets, ProvidesAccessTo, Yields, UsesTool, AuthenticatedWith, ExtractedFrom, Enumerated, Establishes, AccessedFile, Revealed, UsesPayload, OobInteraction

ENTITY_TYPES = {
    'Target': Target,
    'Vulnerability': Vulnerability,
    'Tool': Tool,
    'TechnicalFinding': TechnicalFinding,
    'AttackTechnique': AttackTechnique,
    'TestPhase': TestPhase,
    'Credential': Credential,
    'ExploitCode': ExploitCode,
    'AuthenticationAttempt': AuthenticationAttempt,
    'DatabaseMetadata': DatabaseMetadata,
    'ExploitationAttempt': ExploitationAttempt,
    'SessionInfo': SessionInfo,
    'FileSystemAccess': FileSystemAccess,
    'XMLPayload': XMLPayload,
}

EDGE_TYPES = {
    'HAS_VULNERABILITY': HasVulnerability,
    'USED_AGAINST': UsedAgainst,
    'EXPLOITS': Exploits,
    'DISCOVERED_IN': DiscoveredIn,
    'LEADS_TO': LeadsTo,
    'TARGETS': Targets,
    'PROVIDES_ACCESS_TO': ProvidesAccessTo,
    'YIELDS': Yields,
    'USES_TOOL': UsesTool,
    'AUTHENTICATED_WITH': AuthenticatedWith,
    'EXTRACTED_FROM': ExtractedFrom,
    'ENUMERATED': Enumerated,
    'ESTABLISHES': Establishes,
    'ACCESSED_FILE': AccessedFile,
    'REVEALED': Revealed,
    'USES_PAYLOAD': UsesPayload,
    'OOB_INTERACTION': OobInteraction,
}

EDGE_TYPE_MAP = {
    ('Target', 'Vulnerability'): ['HAS_VULNERABILITY'],
    ('Target', 'TechnicalFinding'): ['YIELDS'],
    ('Target', 'Target'): ['LEADS_TO'],
    ('Vulnerability', 'Target'): ['TARGETS'],
    ('Tool', 'Target'): ['USED_AGAINST'],
    ('Tool', 'TechnicalFinding'): ['YIELDS'],
    ('Tool', 'Vulnerability'): ['YIELDS'],
    ('AttackTechnique', 'Target'): ['USED_AGAINST'],
    ('AttackTechnique', 'Vulnerability'): ['EXPLOITS'],
    ('AttackTechnique', 'Tool'): ['USES_TOOL'],
    ('AttackTechnique', 'AttackTechnique'): ['LEADS_TO'],
    ('TechnicalFinding', 'TestPhase'): ['DISCOVERED_IN'],
    ('TechnicalFinding', 'Vulnerability'): ['LEADS_TO'],
    ('TechnicalFinding', 'TechnicalFinding'): ['LEADS_TO'],
    ('Credential', 'Target'): ['PROVIDES_ACCESS_TO'],
    ('TechnicalFinding', 'Credential'): ['REVEALED'],
    ('ExploitCode', 'Vulnerability'): ['EXPLOITS'],
    ('ExploitCode', 'Target'): ['USED_AGAINST'],
    ('TestPhase', 'TestPhase'): ['LEADS_TO'],
    ('AuthenticationAttempt', 'Target'): ['USED_AGAINST'],
    ('AuthenticationAttempt', 'SessionInfo'): ['ESTABLISHES'],
    ('DatabaseMetadata', 'Target'): ['EXTRACTED_FROM'],
    ('Tool', 'DatabaseMetadata'): ['ENUMERATED'],
    ('ExploitationAttempt', 'Target'): ['USED_AGAINST'],
    ('ExploitationAttempt', 'Vulnerability'): ['EXPLOITS'],
    ('ExploitationAttempt', 'TechnicalFinding'): ['YIELDS'],
    ('SessionInfo', 'Target'): ['PROVIDES_ACCESS_TO'],
    ('Credential', 'Target'): ['AUTHENTICATED_WITH'],
    ('FileSystemAccess', 'Target'): ['EXTRACTED_FROM'],
    ('AttackTechnique', 'FileSystemAccess'): ['ACCESSED_FILE'],
    ('ExploitationAttempt', 'FileSystemAccess'): ['ACCESSED_FILE'],
    ('FileSystemAccess', 'TechnicalFinding'): ['REVEALED'],
    ('FileSystemAccess', 'Credential'): ['REVEALED'],
    ('XMLPayload', 'Vulnerability'): ['EXPLOITS'],
    ('ExploitationAttempt', 'XMLPayload'): ['USES_PAYLOAD'],
    ('XMLPayload', 'Target'): ['USED_AGAINST'],
    ('XMLPayload', 'FileSystemAccess'): ['ACCESSED_FILE'],
    ('XMLPayload', 'TechnicalFinding'): ['OOB_INTERACTION'],
}
